# Generated by Django 4.1.5 on 2023-03-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='phone',
        ),
    ]
