# Generated by Django 4.1.5 on 2023-03-11 03:56

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_rename_firstname_contact_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('photo', models.ImageField(upload_to='blogs/')),
                ('post_by', models.CharField(default='Admin', max_length=50)),
                ('post_on', models.DateField(default=datetime.date(2023, 3, 10))),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
