# Generated by Django 4.1.5 on 2023-03-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_faq_hotel_touristplaces_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='faqs',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='photo',
            new_name='photo3',
        ),
        migrations.RemoveField(
            model_name='touristplaces',
            name='photo',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo1',
            field=models.ImageField(default='', upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo2',
            field=models.ImageField(default='', upload_to='room pic/'),
        ),
        migrations.AddField(
            model_name='touristplaces',
            name='photo1',
            field=models.ImageField(default='', upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='touristplaces',
            name='photo2',
            field=models.ImageField(default='', upload_to='room pic/'),
        ),
        migrations.AddField(
            model_name='touristplaces',
            name='photo3',
            field=models.ImageField(default='', upload_to='reception/'),
        ),
        migrations.AlterModelTable(
            name='faqs',
            table='faqs',
        ),
    ]
