# Generated by Django 4.1.5 on 2023-05-09 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_blogs_post_on_alter_tour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='internationalpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='tour/')),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('no_of_days_nights', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'internationalpackage',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 5, 9)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Religious', 'Religious'), ('Adventurous', 'Adventurous'), ('Honeymoon', 'Honeymoon'), ('Sports', 'Sports'), ('Student', 'Student'), ('Wildlife', 'Wildlife'), ('Hill Station', 'Hill Station'), ('Traditional', 'Traditional'), ('Vocation', 'Vocation')], max_length=200),
        ),
    ]
