# Generated by Django 4.1.5 on 2023-05-09 04:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_internationalpackage_alter_blogs_post_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalpackage',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
