# Generated by Django 4.1.5 on 2023-03-16 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=10)),
                ('maplocation', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='reception/')),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('from_price', models.FloatField()),
                ('to_price', models.FloatField()),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Touristplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addresslocation', models.CharField(max_length=10)),
                ('maplocation', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='reception/')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Touristplaces',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
