# Generated by Django 4.1.5 on 2023-04-01 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='Hotels',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 3, 31)),
        ),
        migrations.AlterModelTable(
            name='hotels',
            table='Hotels',
        ),
    ]
