# Generated by Django 4.1.5 on 2023-04-07 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_hotel_hotels_alter_blogs_post_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phonenumber', models.TextField()),
                ('Emailid', models.TextField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('title', models.TextField()),
                ('noofdays', models.TextField()),
                ('description', models.TextField()),
                ('price', models.TextField()),
            ],
            options={
                'db_table': 'tour',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 6)),
        ),
    ]
