# Generated by Django 4.1.5 on 2023-04-24 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Emailid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='Checkout',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='ContactNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='FirstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='LastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_Adults',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_Children',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='Tourtype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 23)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Religious', 'Religious'), ('Adventurous', 'Adventurous'), ('Honeymoon', 'Honeymoon'), ('Sports', 'Sports'), ('Medical', 'Medical'), ('Student', 'Student'), ('Wildlife', 'Wildlife'), ('Inbound', 'Inbound'), ('Hill Station', 'Hill Station'), ('Traditional', 'Traditional')], max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='EmailId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
