# Generated by Django 4.1.5 on 2023-04-27 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_booking_emailid_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='tour/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
