# Generated by Django 4.1.5 on 2023-04-28 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_tour_image_alter_blogs_post_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Religious', 'Religious'), ('Adventurous', 'Adventurous'), ('Honeymoon', 'Honeymoon'), ('Sports', 'Sports'), ('Medical', 'Medical'), ('Student', 'Student'), ('Wildlife', 'Wildlife'), ('Hill Station', 'Hill Station'), ('Traditional', 'Traditional'), ('Vocation', 'Vocation')], max_length=200),
        ),
    ]
